### ISSUE TITLE
[Feature request] Align departure and arrival times and add total travel time

### ISSUE THREAD

**Issue by olejorgenb** [ErlendEllingsen/ruter-cli#3]
------- Forslag #4 -------
    Departure:  Tue Nov 01 2016 20:04:00 GMT+0100
    Arrival:  Tue Nov 01 2016 20:38:00 GMT+0100

 =>

    ------- Forslag #4 (34min) -------
    Departure:  Tue Nov 01 2016 20:04:00 GMT+0100
    Arrival:    Tue Nov 01 2016 20:38:00 GMT+0100

**Comment by ErlendEllingsen** [comment]
Will implement tonight👍🏼
